[[Fmt]]
arch = "aarch64"
git-tree-sha1 = "6c7d76aa71692f8b178e689780194cc0658a965f"
os = "macos"

    [[Fmt.download]]
    sha256 = "409f647482e97678f2882212c73ec74384a062ef8de9d975a83dcd85472c7b7b"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.aarch64-apple-darwin.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d551a2b5f7d1cd930d829cd89285d87e5c5171c6"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "40895a6495ad29cc5468ff1fdb0cd210c788b75181f32204ea547b15a788cb32"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "001e0774c3cd943a318e0451cdaa7d249f1beb96"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "7becb87ee3304233deab29a407f4aba81439b05bc5a62639c6f6519569842b39"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b08686b146d4c29115878601454e0a598892881e"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "406fe807cea80e2d65cd9b65f1e119df7266ad5efe4948dd26aa79f866031a76"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.aarch64-linux-musl-cxx03.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32ffbb8a2e2c498ab8c87c6f365d26c7da0d7b31"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "162cfdda19c1f8d1370dd12bb2461e12e392ed2767ef08783f953318a8e0ce6e"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bb6254f0ebe0f9003ebdf707fa720d255a1f654"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "302a06bbf619303a5c575f52ec88762667b53e279309c3a12cc6247073cc363b"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e46b1ecba32517b6f1c6437c7a0f51cabce64720"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "13768432c408c4ed9696d23d61698457fd499a378856c6b6d0848c76c92f61ea"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c61914ca00a7fc3e307e2c6f2d13a4ecc9ce062"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "25080996da89fed6154a3228923ccba6fecca45a07a161b2cdfe84c3ec339cb9"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55aa7459deed6c2dd8c5fb2cb7e00a6d8d471ff6"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "eff6833e46d38fbdcd91372c2335b9c6d76a7c62b6b4a6fd1b5e5ce8ddb07b9a"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4de48d00f23d22e72bcbe6c59eb5e9a550b046df"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "c020921264b447a93a3d492bb6207eee266b95d9b3e69788559e5030acd107f8"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e001ba6111c6f00eea3f7fbb1c6955200f9a9e51"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "7a57c71eff9174ada8a3211be0e24252692e349229ac682d4c0963be779709f0"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae4c91b9cb5be0d3da8d043571ecc412219ee1ba"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "1b6f9a35fa033c355842e9aba00889117d73ccbcc62455d594f9ab1f32db31e0"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2a427825ab9e54150aa516bfdbe42a9f03f46b6"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "6824d43bac92a88bc67f9a6646388c43bee3a4afac12ad6f2ed90785b2670703"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f28442b36b8b2168a54e1f645f8121118d121461"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "7795ad1cd3c7dc27ee0f49ea119aec237968d370120a3dd45f81d7046527d267"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.i686-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "883c11cff03262fdb9ca0d221e4e124b9245c7ef"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "6c9de8097283f78e7d7357908b7a48855ec8ae9b9375ae97c414b3655d536ac0"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.i686-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85b68a1ca9c68596a9cf797dc4847e047eb74661"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "e8fcc528fb816c197aed4e34356256fa7d94638285325456c011926ccd7db51f"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.i686-linux-musl-cxx03.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4721ee817401c234be183f9dc91c5e8ea32b0230"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "3d8a35cd3718f185c5786ab3744fb47019cb3418fd45738c182c64203eab2c1c"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.i686-linux-musl-cxx11.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4baff72dd485cfc20b535d2f8d8943d9f8738aa"
os = "windows"

    [[Fmt.download]]
    sha256 = "534150020dd30cbe035b65cbe538f976245b044de061aa22b922a80c463c7ece"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.i686-w64-mingw32-cxx03.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d593ba7abd3b54cdb7950764bdc8a14a63851ef"
os = "windows"

    [[Fmt.download]]
    sha256 = "bb5672de77732ab557d149270cc086064641dcd3ff3ade957fc5656d84791197"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[Fmt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1ec2ca92f0352539ed2590e04c7a1f6aa9fe6a1"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "15e93abd5586bda02678c9b422711d216374f800595fd384c947cbfffd2b2eec"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54aaf29d18155371d099619bd191de035edb29d1"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "7a87f6447d97a355caae02f0484740f15d78e85005ab5bf107482158a90120e1"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "x86_64"
git-tree-sha1 = "eb7e5a3b090b1c4eddee926f1432679be5a18ea7"
os = "macos"

    [[Fmt.download]]
    sha256 = "c2016590d549411567366bbf592e88a392f39d1e9bb61b8cfd54eea38d13617e"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-apple-darwin.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "092102b8e5c84c30c8e9093615f489bb6a75300e"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "651e493826dbc26cc18117659305de9676f6c6e0468cf0e740a23a5e12f19e0f"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fac29b597d087ae2fee90ff81219c4261cc760b"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "2a5ec9d64140fe4d8252288a9e4b99dd24b501bbf83947f8e706676804cd6ea4"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f63f3c4a9037f0311ae43797c2ab8d70e0e0ca4"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "b38ed24e7bbe53324c3499209147f882dc0069575891c91c7b76fe50ac29d835"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-linux-musl-cxx03.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75c94b536db3952946b46675518284e78b7d2db2"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "8a07c0ef63f57e31e48cd2df6300daad8103f3be91ef8685b564c33b496aa907"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[Fmt]]
arch = "x86_64"
git-tree-sha1 = "93c3d31f6197303947cd4346ce0f10116db9b1a4"
os = "freebsd"

    [[Fmt.download]]
    sha256 = "3a154005e63af025dd4f0020f523562685598b8651c33c391900b0697a382b8a"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-unknown-freebsd.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8db625047b0c178c440e52f9cab1f25d6b39110"
os = "windows"

    [[Fmt.download]]
    sha256 = "9b3c47a1dca09b165332bd86619e019409cb45223563136e45200a7833fe03ef"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6beffe654e2e6732f8aed145a6f7b61104561390"
os = "windows"

    [[Fmt.download]]
    sha256 = "f95101ad666b31789131a601aa3441944c9de52c3fa83a3e1523a3fa88e26ba7"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.0.2+0/Fmt.v11.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
