[[Fmt]]
arch = "aarch64"
git-tree-sha1 = "78ae4551c948612525ff962df32f2b811ab2b95e"
os = "macos"

    [[Fmt.download]]
    sha256 = "48687e1d58d0c6acdc1029fcf8c4690e99556423cd9aada583cd8dee52d1303f"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.aarch64-apple-darwin.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f760fcafe25bab51f1023409d31164347dd33761"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "792a0bb1437a0f083f8db61624ddbe2edea6f6cdf8285195c8b818e57b5d4549"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7439891e11f62df59bc52c41f99f827049bb5a3f"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "f0835f395ea4d19f09bbd0982b9eafe32cc94b5e224f6424512f7d1420ec5e7c"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1325d6c2d082f351f75d9dbcb1103b86d06b461"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "714090bd837233c576428f4b31a0dccdc2a6cfab679310d1adbff0e91ca4d56f"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[Fmt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba30f17db716603bd852a62fa157394b2ca30c66"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "5dc173d3b7bcc11333817fa48dfb00eefc8c034fd9dd582a5d4d300a521ad303"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[Fmt]]
arch = "aarch64"
git-tree-sha1 = "25d4126abc41f2c5f87a6597e496a7a27a824265"
os = "freebsd"

    [[Fmt.download]]
    sha256 = "b9539ade8041cf185d443b7b7fcfef458308eee605675ed2967505ba24a0e914"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.aarch64-unknown-freebsd.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b701d396a08528618ece94f0fbaa5ba7306c4e2e"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "66a00445a44770a9383ee0f7643f789d33a10a290dcc6e5b9edc4708f75ca450"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89cb90e42a2f4f8ae4f41336b0c735cbb95a189f"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "34c18c7c85befddbbb06b8cda7561dde209591bfe902c522e2c419e78c68b8dd"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb7df455763b99e3e01f9816428d1c2e8e2acc93"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "d49b23ccd9390db31b9ffbda8186f73baa43d6236178e80ef38747641483ad1c"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92edffc6cc2952f39a305c46e961e0928522d3ab"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "e563ef9fd8a03762d41d67357bd870903d378a39444f9333992f125a203f56d9"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "580a868ee2e4b216ed6f925cbef6c79401189ae5"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "667010e459b92f289ea6686594c2ba36cfe7e525cb12720eb3fa2c0804e6e046"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfae6d920bccf751b9741fd2ce1b3956e7b7729e"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "12635dd3bbd595f92166a17d7f4da774fbc3089b51980c2b022e425e70d2b475"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ce8d12e81f7135d23c2863c328cef7ecaf4dee8"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "b7606ad2508ba26aac7650ac89efd7850932a1711526026ed29aaaa5fc6e60d9"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Fmt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aa184a0c49e760be33e0b01cb8f86e71d9f0e63"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "86fb9f2fdf6e16f86b3be43dc0edbac5416a3eb005db91741fa863875726870d"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daa40fa037778e55c69833e7276a5dd583a66d24"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "ee423c8c28d59e021d715c306b75865416b37ffeab63152ce822311340a10645"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.i686-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d3ddb835feeac81853670c0592610c7ab301047"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "fc2ae399c478cdaf9c0703f3291cc1f3bb041c602bc54b1fea938db7338fc3fc"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.i686-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7626719d7a3ce896a88c5d2c36a3f3062732ed9"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "350915ceb13d07f9c800e14c8016f449a067acf19999e5c3c0b9b22cfcb37df4"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.i686-linux-musl-cxx03.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab2948e540fe95aca1eeadc0cd35ec8e6687f41a"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "a6719c7ba33fe1a979b51deaaa06ff34e353eb0fbc33ffdfa48ad0f897eb8d78"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.i686-linux-musl-cxx11.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d0e6cf12e5f3da8e574445989c962c5ca1759d4"
os = "windows"

    [[Fmt.download]]
    sha256 = "5b63abac62ab1e9af37342a828ca467f4cd33d032ef7e815bc300d5ac6715c9b"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[Fmt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7003e019119ab159dc609a55df131c332a1178d9"
os = "windows"

    [[Fmt.download]]
    sha256 = "9054033ae046cb89d187c5f30c35f53495c97aad9c0712046e15cd2a0ad9d616"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[Fmt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8214895705f0295b175146e42a4df3d80244b4ce"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "69458f27d73dd12546ebfaeb22c0e34b92071ae604a0f24f288ba495a837193a"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9f6afa8807802ae22418fb3004a385e7d3ad3a1"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "b9b5709656d3d43a3fae56c0ddd100b835d6e4da5a19d38a691185b63a0edce1"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42cd465dce4121946e3630c73a1a0e535688884f"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "8bac132970ac2c41701db0abe1d29f958612aa76557414108d1f22336efea7e2"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.riscv64-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f00d0a767f0ec6fe9970b19173b9c6760a3c162e"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "28d22908a7ab227cd6556a418c5a982066cf87f15eb90e9864607e199f8cfd7b"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "x86_64"
git-tree-sha1 = "da9a9048597c0239cf262c35932197979a251376"
os = "macos"

    [[Fmt.download]]
    sha256 = "adfe6dfafb609b9e56fac08922fd497d80ee3389170f84a75fde875bba2f0950"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-apple-darwin.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e353d54be70670eb5c5004540c3984488d54fcbd"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "419dbb1973871259d4de77a768fee22dea073619e0fcadd0c0edf5c2a8419f49"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "469214bd5d24890d48e1f3a640410801e5e73cdd"
libc = "glibc"
os = "linux"

    [[Fmt.download]]
    sha256 = "76fb6ef1981591c6ea5df766236c570b3cb7c0476cc9364e014eb257b3e13548"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca971131479d1dd9c95375d5358dadeaf81fac8b"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "b231a29f95c24f30bba03fb9250221c3429e2fa5e9bbc4a258aec89ab2baea65"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b126c7f4a0ed7bef2b38dd2b8088f781e25d15ff"
libc = "musl"
os = "linux"

    [[Fmt.download]]
    sha256 = "2e5eeae501816d24b52d1e74165e2d754fe01c229dd0c401979154283a47779e"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[Fmt]]
arch = "x86_64"
git-tree-sha1 = "d46c09a05a4f6f3a857fcc341422af6ccebedca8"
os = "freebsd"

    [[Fmt.download]]
    sha256 = "6b2db3065efc01ef81253b251fdd7fffbbaa86e981d65487712bd1634a58e3bb"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-unknown-freebsd.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38e8fa762c154e491563040deeef3f383f53d8b7"
os = "windows"

    [[Fmt.download]]
    sha256 = "eb46f4ed7d47f3a89c4498f3507af627bcfa0a584df76d5e31e0de8d53183631"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Fmt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cca0c62ae82bb4e5b7300b97661c1c75f5a0277"
os = "windows"

    [[Fmt.download]]
    sha256 = "16d4716b7ae95c0a1b3581451e1f33b3f0661fa63e05116d32c3096eae07ee63"
    url = "https://github.com/JuliaBinaryWrappers/Fmt_jll.jl/releases/download/Fmt-v11.1.1+0/Fmt.v11.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
