# Autogenerated wrapper script for Fmt_jll for x86_64-w64-mingw32-cxx11
export libfmt

JLLWrappers.@generate_wrapper_header("Fmt")
JLLWrappers.@declare_library_product(libfmt, "libfmt.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfmt,
        "bin\\libfmt.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
